# Generated by Django 5.2.6 on 2025-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], help_text="Genre de l'utilisateur", max_length=1)),
                ('orientation', models.CharField(choices=[('HET', 'Hétéro'), ('HOM', 'Homosexuel'), ('BI', 'Bisexuel(le)'), ('ATR', 'Autre')], help_text='Orientation sexuelle', max_length=3)),
                ('age', models.PositiveBigIntegerField(blank=True, help_text='Âge temporaire, à synchroniser avec users plus tard', null=True)),
                ('bio', models.TextField(blank=True, help_text="Bio de l'utilisateur", max_length=500)),
                ('location', models.CharField(blank=True, help_text="Ville de l'utilisateur", max_length=100)),
                ('interest', models.TextField(blank=True, help_text="Centre d'intérêt séparé par des virgules")),
                ('looking_for', models.CharField(choices=[('SERIOUS', 'Pour la vie'), ('ONE_NIGHT', 'Pour une nuit'), ('DRINK', 'Pour un verre'), ('TALK', 'Pour discuter')], help_text='Intention de rencontre', max_length=20)),
            ],
        ),
    ]
