# Generated by Django 5.2.6 on 2025-09-16 09:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], default='H', help_text="Genre de l'utilisateur", max_length=1)),
                ('orientation', models.CharField(choices=[('HET', 'Hétéro'), ('HOM', 'Homosexuel'), ('BI', 'Bisexuel(le)'), ('ATR', 'Autre')], default='HET', help_text='Orientation sexuelle', max_length=3)),
                ('age', models.PositiveSmallIntegerField(help_text="Âge de l'utilisateur", null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)])),
                ('bio', models.TextField(blank=True, help_text="Bio de l'utilisateur", max_length=500)),
                ('photo', models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='photos/%Y/%m')),
                ('location', models.CharField(blank=True, help_text="Ville de l'utilisateur", max_length=100)),
                ('looking_for', models.CharField(choices=[('SERIOUS', 'Pour la vie'), ('ONE_NIGHT', 'Pour une nuit'), ('DRINK', 'Pour un verre'), ('TALK', 'Pour discuter')], help_text='Intention de rencontre', max_length=20)),
                ('interests', models.ManyToManyField(blank=True, to='profiles.interest')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
