# Generated by Django 5.2.6 on 2025-09-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='profiles.interest'),
        ),
    ]
