# Generated by Django 5.2.6 on 2025-09-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_memberprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, help_text='Âge temporaire, à synchroniser avec users plus tard', null=True),
        ),
    ]
