# Generated by Django 5.2.6 on 2025-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_memberprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='media/photos'),
        ),
    ]
