# Generated by Django 5.2.6 on 2025-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_memberprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='age',
            field=models.PositiveBigIntegerField(help_text='Âge temporaire, à synchroniser avec users plus tard', null=True),
        ),
    ]
