# Generated by Django 5.2.6 on 2025-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_memberprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Âge temporaire, à synchroniser avec users plus tard', null=True),
        ),
    ]
