# Generated by Django 5.2.6 on 2025-09-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_memberprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Âge temporaire, à synchroniser avec users plus tard', null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='photos/%Y/%m'),
        ),
    ]
