# Generated by Django 5.2.6 on 2025-09-11 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('ES', 'Spanish'), ('DE', 'German')], default='FR', help_text='Language', max_length=10)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone', null=True)),
                ('birth_date', models.DateField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
