# Generated by Django 5.2.6 on 2025-09-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_accountuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountuser',
            old_name='username',
            new_name='user',
        ),
    ]
