# Generated by Django 5.2.6 on 2025-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_accountuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='language',
            field=models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('ES', 'Spanish'), ('DE', 'German')], default='FR', help_text='Language', max_length=10),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone', null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
